### ISSUE TITLE
package duplicated in keycloak libraries

### ISSUE THREAD

**Issue by CiscoFR** [rsatrio/Keycloak-Federation-ExistingDB#1]
Hi,
I'm trying to use your code for an user federation in keycloak 19.0.3.

I'm having problems with de jar dependencies. 
The needed libraries are: core, server-spi, model-legacy and common (in your pom only are detailed the first 2, maybe an older version of keycloak?).
But the same package is refered in differents jar, a JPMS problem. I checked other versions: 20, 18, but the problem persist.

How can I solve this?

Thanks,
Cisco

**Comment by rsatrio** [comment]
Hi @CiscoFR , can you be more detailed about your problem? I'm creating this plugin for Keycloak 11, and I think it will still worked up to Keycloak 14

**Comment by 10101010101010001** [comment]
@rsatrio Could you update this to work in newer versions of Keycloak? Thank you.

**Comment by CiscoFR** [comment]
> Hi @CiscoFR , can you be more detailed about your problem? I'm creating this plugin for Keycloak 11, and I think it will still worked up to Keycloak 14

Hi,

sorry I didn't recived notification of your response.

The problem is that I cannot compile with the conflict of classes duplicated in different jars.
Attached one capture of error with the 3 jars needed to compile the .java
 
![image](https://user-images.githubusercontent.com/117357824/207576132-a49bd823-9726-4d53-a13a-4c0bd4315d44.png)

Thanks,
Cisco

**Comment by 10101010101010001** [comment]
@CiscoFR Checkout [user-storage-jpa from keycloak-quickstart](https://github.com/keycloak/keycloak-quickstarts/tree/latest/user-storage-jpa) and [user-provider by dasniko](https://github.com/dasniko/keycloak-extensions-demo/tree/main/user-provider).  I was able to successfully get a working UserStorageProvider that used a hibernate persistence jpa/jta entity objects.
