### ISSUE TITLE
Not able to login with external db user

### ISSUE THREAD

**Issue by HimanshuNauti** [rsatrio/Keycloak-Federation-ExistingDB#4]
What should I write in my JNDI name

"Database JNDI name: The JNDI name of the datasource you want to use (example: java:jboss/datasources/UserDS)"

I have configured this in conf file

db-url=jdbc:sqlserver://localhost;databaseName=newabc;encrypt=false;
db-username=him
db-password=root

**Comment by rsatrio** [comment]
Hi @HimanshuNauti , you have to do this :
![image](https://github.com/rsatrio/Keycloak-Federation-ExistingDB/assets/14831786/7f7543d5-8dcf-4c94-bc00-2f20e8294c66)

So you have to install jdbc driver of Sql Server and find out how to jndi url for that database
